#cloud-config
# https://docs.cloud-init.io/en/latest/reference/examples.html#yaml-examples
# Update apt database on first boot (run 'apt-get update').
# Note, if packages are given, or package_upgrade is true, then
# update will be done independent of this setting.
#
# Default: false
# package_update: true
# package_upgrade: true

# packages:
#     - gcc

write_files:
  - path: /run/run-conda-environment.sh
    content: |
      #!/bin/bash
      
      echo "From script" >> /root/runcmd_log.txt
      
      . /etc/miniconda/etc/profile.d/conda.sh
      . /root/setup_environment.sh
      
      which python3 >> /root/runcmd_log.txt
      which conda >> /root/runcmd_log.txt
      
      echo "GRIZLI: ${GRIZLI}" >> /root/runcmd_log.txt

      conda run -n py312 python3 -c "import unik; print('unik: ', unik.__version__)" >> /root/runcmd_log.txt
      conda run -n py312 python3 -c "import grizli; print('grizli: ', grizli.__version__)" >> /root/runcmd_log.txt
      
      echo "yPATH ${PATH}" >> /root/runcmd_log.txt
      
      cd /root/scaleway-dja
      git pull
      
      cd /GrizliImaging/
      
      # conda run -n py312 python3 $HOME/scaleway-dja/processor-instance/app/app.py --msa
      
      echo 'Script executed successfully!' >> /run/run_testing.txt
      
    permissions: '0755'
        
# Runs on boot
bootcmd:
    - date >> /root/bootcmd_log.txt
    - ls /root/ >> /root/bootcmd_log.txt
    - [ bash, "/root/boot-conda-environment.sh"]
    
# Runs later in the process but just the first time
runcmd:
    - date >> /root/runcmd_log.txt
    - ls /root/ >> /root/runcmd_log.txt
    - [ bash, "/run/run-conda-environment.sh"]
#    - git clone "https://github.com/gbrammer/scaleway-dja.git" /root/scaleway-dja
