#cloud-config
# https://docs.cloud-init.io/en/latest/reference/examples.html#yaml-examples
# Update apt database on first boot (run 'apt-get update').
# Note, if packages are given, or package_upgrade is true, then
# update will be done independent of this setting.
#
# Default: false
# package_update: true
# package_upgrade: true

# packages:
#     - gcc

write_files:
  - path: /run/run-conda-environment.sh
    content: |
      #!/bin/bash
      
      echo "From script" >> /root/runcmd_log.txt
      
      . /etc/miniconda/etc/profile.d/conda.sh
      . /root/setup_environment.sh
      
      which python3 >> /root/runcmd_log.txt
      which conda >> /root/runcmd_log.txt
      
      echo "GRIZLI: ${GRIZLI}" >> /root/runcmd_log.txt

      conda run -n py312 python3 -c "import unik; print('unik: ', unik.__version__)" >> /root/runcmd_log.txt
      conda run -n py312 python3 -c "import grizli; print('grizli: ', grizli.__version__)" >> /root/runcmd_log.txt
      
      echo "yPATH ${PATH}" >> /root/runcmd_log.txt
      
      cd /root/scaleway-dja
      git pull
      
      echo "source /root/scaleway-dja/processor-instance/app/bash_extras.sh" >> ~/.bashrc

      # Patch extract2d
      cat <<EOF > /root/nirspec_2d.patch
      85c85,88
      <             new_model, xlo, xhi, ylo, yhi = process_slit(input_model, slit, exp_type)
      ---
      >             try:
      >                 new_model, xlo, xhi, ylo, yhi = process_slit(input_model, slit, exp_type)
      >             except ValueError:
      >                 continue
      EOF
      
      patch /etc/miniconda/envs/py312/lib/python3.12/site-packages/jwst/extract_2d/nirspec.py /root/nirspec_2d.patch

      echo 'Script executed successfully!' >> /run/run_testing.txt
      
    permissions: '0755'

  - path: /root/run-processor-cron.sh
    content: |
        #!/bin/bash

        . /etc/miniconda/etc/profile.d/conda.sh
        . /root/setup_environment.sh

        cd /GrizliImaging/

        max_locks=`scw-userdata max_process_locks`
        app_types=`scw-userdata app_process_types | sed "s/_/ /g"`

        for app in ${app_types}; do
            count_lockfiles=`ls *lock | wc -l`

            if [[ $count_lockfiles -lt $max_locks ]]; then
                msg="Found ${count_lockfiles} lock files >> run app.py --${app}"
                echo `date` ${msg} >> /GrizliImaging/cron.log.txt
                conda run -n py312 python3 /root/scaleway-dja/processor-instance/app/app.py --${app}
            else
                echo "Found ${count_lockfiles} lock files" >> /GrizliImaging/cron.log.txt
            fi
        done
        
    permissions: '0755'

# Runs on boot
bootcmd:
    - date >> /root/bootcmd_log.txt
    - ls /root/ >> /root/bootcmd_log.txt
    # - [ bash, "/root/boot-conda-environment.sh"]
    
# Runs later in the process but just the first time
runcmd:
    - date >> /root/runcmd_log.txt
    - ls /root/ >> /root/runcmd_log.txt
    - [ bash, "/run/run-conda-environment.sh"]
    - (crontab -l 2>/dev/null || echo ""; echo "* * * * * /root/run-processor-cron.sh") | crontab -
